---
# make sure to
# module load gcc/7.3.0  mvapich2/2.3rc2 boost

- name: Install gudhi dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
    name: "{{ item }}"
  with_items:
    - libboost-all-dev

# Will only download once
- name: Get gudhi
  get_url:
    url: "{{ gudhi_url }}"
    dest: "{{ gudhi_code_folder }}/{{ gudhi_src_archive }}"
  register: gudhi_download

- name: Extract gudhi source
  unarchive:
    src: "{{ gudhi_download.dest }}"
    dest: "{{ gudhi_code_folder }}"
    remote_src: true
    # when: gudhi_download.changed

- name: Create build dir
  file:
    path: "{{ gudhi_topdir }}/build"
    state: directory

- name: run cmake
  shell: CC=gcc CXX=g++ cmake ..
  args:
    chdir: "{{ gudhi_topdir }}/build"
    creates: "{{ gudhi_topdir }}/build/Makefile"

- name: make gudhi
  make:
    chdir: "{{ gudhi_topdir }}/build"

# - import_tasks: tests.yml
#   when: gudhi_make.changed and run_tests is defined and run_tests

- name: "Put a line in ~/.profile to add gudhi to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ gudhi_topdir }}/build/utilities/Rips_complex"
